/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author delri
 */
public class ViewMenuAdm extends javax.swing.JFrame {

    /**
     * Creates new form ViewMenu
     */
    public ViewMenuAdm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuSair = new javax.swing.JMenuItem();
        menuDesconectar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuUser = new javax.swing.JMenuItem();
        menuFuncao = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuCachaca = new javax.swing.JMenuItem();
        menuOvo = new javax.swing.JMenuItem();
        menuRapadura = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/24991260_1447296308732219_2500876749384716373_n (2).jpg"))); // NOI18N

        jMenu1.setText("Arquivo");

        menuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Resize16/error.png"))); // NOI18N
        menuSair.setText("Sair");
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });
        jMenu1.add(menuSair);

        menuDesconectar.setText("Desconectar");
        menuDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDesconectarActionPerformed(evt);
            }
        });
        jMenu1.add(menuDesconectar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Colaboradores");

        menuUser.setText("Usuários");
        menuUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUserActionPerformed(evt);
            }
        });
        jMenu2.add(menuUser);

        menuFuncao.setText("Funções");
        menuFuncao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFuncaoActionPerformed(evt);
            }
        });
        jMenu2.add(menuFuncao);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Cadastro");

        menuCachaca.setText("Cachaça");
        jMenu3.add(menuCachaca);

        menuOvo.setText("Ovo");
        menuOvo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOvoActionPerformed(evt);
            }
        });
        jMenu3.add(menuOvo);

        menuRapadura.setText("Rapadura");
        jMenu3.add(menuRapadura);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Venda");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jLabel1)
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void Voltar(){
        ViewLogin login = new ViewLogin();
        login.pack();
        login.setLocationRelativeTo(null);
        login.setVisible(true);
        ViewMenuAdm.this.dispose();
    }
    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menuSairActionPerformed

    private void menuUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUserActionPerformed
        // TODO add your handling code here:
        ViewGerenciarUsuario user = new ViewGerenciarUsuario();
        user.pack();
        user.setLocationRelativeTo(null);
        user.setVisible(true);
        ViewMenuAdm.this.dispose();
    }//GEN-LAST:event_menuUserActionPerformed

    private void menuFuncaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFuncaoActionPerformed
        // TODO add your handling code here:
        ViewGerenciarFuncao func = new ViewGerenciarFuncao();
        func.pack();
        func.setLocationRelativeTo(null);
        func.setVisible(true);
        ViewMenuAdm.this.dispose();
    }//GEN-LAST:event_menuFuncaoActionPerformed

    private void menuOvoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOvoActionPerformed
        // TODO add your handling code here:
        ViewGerenciarOvos ovo = new ViewGerenciarOvos();
        ovo.pack();
        ovo.setLocationRelativeTo(null);
        ovo.setVisible(true);
        ViewMenuAdm.this.dispose();
    }//GEN-LAST:event_menuOvoActionPerformed

    private void menuDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDesconectarActionPerformed
        // TODO add your handling code here:
        Voltar();
    }//GEN-LAST:event_menuDesconectarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewMenuAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewMenuAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewMenuAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewMenuAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewMenuAdm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuCachaca;
    private javax.swing.JMenuItem menuDesconectar;
    private javax.swing.JMenuItem menuFuncao;
    private javax.swing.JMenuItem menuOvo;
    private javax.swing.JMenuItem menuRapadura;
    private javax.swing.JMenuItem menuSair;
    private javax.swing.JMenuItem menuUser;
    // End of variables declaration//GEN-END:variables
}
